package extensions

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// The re-probe of a generated custom integration's commands: the command
// list was derived once, at connect time, from the executable's own
// `--help`; when the tool ships a new version its subcommands and flags may
// have moved. Re-running the derivation regenerates the static descriptor
// in place — the current one stays authoritative for everything
// user-visible (ids, names, the provider block), and only the derived
// argument arrays and the subcommand list are rebuilt. A tool that no
// longer answers its help the way it did keeps the previous descriptor.

// helpProbeFile is the sidecar beside the descriptor recording when the
// command list was last derived, and how its size moved — the facts the
// drawer's freshness line reports. Read back for display only.
const helpProbeFile = "help-probe.json"

// ErrNotGenerated is what a re-probe reports for an integration the host
// did not generate: only those carry a derivation the host may rebuild.
var ErrNotGenerated = errors.New("extensions: the integration was not generated by this host and cannot be re-probed")

// ErrNoExecutable is what a re-probe reports for a tool whose executable
// is not available: reconnecting owns that state.
var ErrNoExecutable = errors.New("extensions: the tool's executable is not available")

// HelpProbeRecord is the freshness sidecar beside a generated descriptor.
type HelpProbeRecord struct {
	ProbedAt int64 `json:"probedAt"`
	// RootArguments and Subcommands are what the last derivation produced.
	RootArguments int `json:"rootArgumentCount"`
	Subcommands   int `json:"subcommandCount"`
	// CommandCount is the descriptor's total (root + subcommands), and
	// PreviousCommandCount the one before it — nil on a first probe, which
	// the drawer shows as unknown rather than a fabricated delta.
	CommandCount         *int `json:"commandCount,omitempty"`
	PreviousCommandCount *int `json:"previousCommandCount,omitempty"`
}

// readHelpProbeRecord reads the sidecar beside a package root's
// descriptor. Best-effort by contract: a missing or unparsable sidecar is
// nil, and the drawer falls back to its unknown state. Purely a read.
func readHelpProbeRecord(packageRoot string) *HelpProbeRecord {
	data, err := os.ReadFile(filepath.Join(packageRoot, helpProbeFile))
	if err != nil {
		return nil
	}
	var record HelpProbeRecord
	if json.Unmarshal(data, &record) != nil {
		return nil
	}
	return &record
}

// writeHelpProbeRecord stages the sidecar for a fresh derivation. The
// previous command count comes off the record it replaces, so the drawer
// can say how the list moved; a first probe has nothing to compare to.
func writeHelpProbeRecord(packageRoot string, derivation HelpDerivation, commandCount int) error {
	previous := (*int)(nil)
	if before := readHelpProbeRecord(packageRoot); before != nil && before.CommandCount != nil {
		previous = before.CommandCount
	}
	record := HelpProbeRecord{
		ProbedAt:             time.Now().Unix(),
		RootArguments:        len(derivation.RootArguments),
		Subcommands:          len(derivation.Subcommands),
		CommandCount:         &commandCount,
		PreviousCommandCount: previous,
	}
	data, err := json.MarshalIndent(record, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(filepath.Join(packageRoot, helpProbeFile), data, 0o644)
}

// ReprobeReport is what a successful re-probe hands back: the sizes of the
// fresh derivation and how the command list moved.
type ReprobeReport struct {
	RootArguments        int
	Subcommands          int
	CommandCount         int
	PreviousCommandCount *int
}

// isGeneratedIntegration reports whether the host itself generated an
// integration's package: its publisher is the local user and its package
// directory is the `integration` dir the connect flow creates. Anything
// else is publisher content a re-probe must never overwrite.
func isGeneratedIntegration(integration Integration) bool {
	if integration.Entry.PublisherID != "local-user" || integration.Entry.ProviderKind != "static-descriptor" {
		return false
	}
	return filepath.Base(integration.PackageDir()) == "integration"
}

// ReprobeCommands re-runs the connect-time help derivation for a generated
// custom integration and regenerates its static descriptor in place. The
// refreshed descriptor replaces the old one atomically (temp + rename) and
// the freshness sidecar is refreshed best-effort. Unlike the connect-time
// derivation, a tool that no longer produces usable help is an error, so
// the previous descriptor is kept.
func ReprobeCommands(ctx context.Context, paths Paths, id string) (ReprobeReport, error) {
	integration, ok := LoadInventory(paths).WithID(id)
	if !ok {
		return ReprobeReport{}, ErrNoIntegration
	}
	if !isGeneratedIntegration(integration) {
		return ReprobeReport{}, ErrNotGenerated
	}
	if integration.Manifest.Runtime.Type == "script" {
		return ReprobeReport{}, errors.New("extensions: script integrations have no executable to probe")
	}
	executable := integration.Entry.ExecutablePath
	if executable == "" {
		return ReprobeReport{}, ErrNoExecutable
	}
	if _, err := os.Stat(executable); err != nil {
		return ReprobeReport{}, fmt.Errorf("%w: %v", ErrNoExecutable, err)
	}
	root := integration.PackageDir()
	if root == "" {
		return ReprobeReport{}, ErrNotGenerated
	}
	descriptorPath := filepath.Join(root, "provider-description.json")
	data, err := os.ReadFile(descriptorPath)
	if err != nil {
		return ReprobeReport{}, fmt.Errorf("extensions: cannot read the custom descriptor: %w", err)
	}
	descriptor, err := ParseDescription(data)
	if err != nil {
		return ReprobeReport{}, fmt.Errorf("extensions: cannot parse the custom descriptor: %w", err)
	}
	if len(descriptor.Commands) == 0 {
		return ReprobeReport{}, errors.New("extensions: the custom descriptor has no commands")
	}
	rootCommand := descriptor.Commands[0]

	// The executable's own binding: the recorded path (or the search path).
	binding, err := ResolveRuntime(integration)
	if err != nil {
		return ReprobeReport{}, fmt.Errorf("extensions: %w", err)
	}
	// The real View's help probe: the same derivation the connect flow ran.
	derivation := probeDeriveWith(ctx, binding, integration)

	// A derivation that understood nothing means the tool is not answering
	// its help the way it did at connect time: keep the old descriptor.
	if derivation.Empty() {
		return ReprobeReport{}, errors.New("extensions: the tool did not produce usable help output")
	}

	descriptor.Commands = derivedCommands(rootCommand, derivation)
	commandCount := len(descriptor.Commands)
	previous := (*int)(nil)
	if before := readHelpProbeRecord(root); before != nil {
		previous = before.CommandCount
	}

	// Atomic replace: stage beside the descriptor, rename over it.
	out, err := json.MarshalIndent(descriptor, "", "  ")
	if err != nil {
		return ReprobeReport{}, fmt.Errorf("extensions: cannot serialize the refreshed descriptor: %w", err)
	}
	out = append(out, '\n')
	temp := filepath.Join(root, ".provider-description.reprobing.tmp")
	if err := os.WriteFile(temp, out, 0o644); err != nil {
		return ReprobeReport{}, fmt.Errorf("extensions: cannot stage the refreshed descriptor: %w", err)
	}
	if err := os.Rename(temp, descriptorPath); err != nil {
		os.Remove(temp)
		return ReprobeReport{}, fmt.Errorf("extensions: cannot update the custom descriptor: %w", err)
	}
	// The sidecar is display only: a failure to write it never undoes the
	// descriptor the user's tool now answers with.
	_ = writeHelpProbeRecord(root, derivation, commandCount)
	return ReprobeReport{
		RootArguments:        len(derivation.RootArguments),
		Subcommands:          len(derivation.Subcommands),
		CommandCount:         commandCount,
		PreviousCommandCount: previous,
	}, nil
}

// probeDeriveWith runs the connect-time derivation against an explicit
// runtime binding: the re-probe's executable may live where the search
// path does not name it.
func probeDeriveWith(ctx context.Context, binding RuntimeBinding, integration Integration) HelpDerivation {
	rootText := ProbeHelpText(ctx, binding, integration, "--help")
	if rootText == "" {
		return HelpDerivation{}
	}
	derivation := HelpDerivation{RootArguments: DeriveArguments(rootText)}
	candidates := DeriveSubcommands(rootText)
	if len(candidates) > maxSubcommandProbes {
		candidates = candidates[:maxSubcommandProbes]
	}
	for _, candidate := range candidates {
		candidate := candidate
		text := ProbeHelpText(ctx, binding, integration, candidate.Name, "--help")
		if text == "" {
			text = ProbeHelpText(ctx, binding, integration, candidate.Name, "-h")
		}
		if text != "" {
			candidate.Arguments = DeriveArguments(text)
		}
		derivation.Subcommands = append(derivation.Subcommands, candidate)
	}
	return derivation
}

// derivedCommands rebuilds the descriptor's command list from a fresh
// derivation: the root command carries its own identity and args prefix,
// and each derived subcommand becomes one runnable command of the same
// execution shape with its name appended.
func derivedCommands(root Command, derivation HelpDerivation) []Command {
	root.Arguments = derivedArguments(derivation.RootArguments)
	commands := []Command{root}
	for _, sub := range derivation.Subcommands {
		if sub.Name == root.ID {
			continue
		}
		prefix := append(append([]string{}, root.Execution.ArgsPrefix...), sub.Name)
		description := sub.Description
		if description == "" {
			description = "Subcommand of " + root.Name
		}
		commands = append(commands, Command{
			ID:          sub.Name,
			Name:        root.Name + " " + sub.Name,
			Description: description,
			Aliases:     sub.Aliases,
			Execution: Execution{
				Program:    root.Execution.Program,
				ArgsPrefix: prefix,
				Mode:       root.Execution.Mode,
			},
			Arguments: derivedArguments(sub.Arguments),
		})
	}
	return commands
}

// derivedArguments converts the derivation's hints into the schema's
// argument shape.
func derivedArguments(arguments []DerivedArgument) []Argument {
	out := make([]Argument, 0, len(arguments))
	for _, argument := range arguments {
		out = append(out, Argument{
			Names:       argument.Names,
			Kind:        argument.Kind,
			Description: argument.Description,
			TakesValue:  argument.TakesValue,
			ValueHint:   argument.ValueHint,
		})
	}
	return out
}
