import { AlertCircle, AlertTriangle, Check, LoaderCircle, Package, ShieldCheck } from "lucide-react";
import type { MouseEvent, RefObject } from "react";
import type { Translate } from "../i18n";
import type { InstallRequest, PermissionReview, SearchResult } from "../ExtensionsPanel";

export type PendingInstall = { result: SearchResult; request: InstallRequest; review: PermissionReview };
export type PendingLocal = { review: PermissionReview; request: InstallRequest; name: string; runtime: string; platforms: string[]; source: string };

type InstallProps = { pending: PendingInstall; busy: boolean; t: Translate; onCancel: () => void; onConfirm: () => void; stopPropagation: (event: MouseEvent) => void; deprecationDescription: (value: string) => string; dialogRef: RefObject<HTMLElement | null> };
type LocalProps = { pending: PendingLocal; busy: boolean; t: Translate; onCancel: () => void; onConfirm: () => void; stopPropagation: (event: MouseEvent) => void; dialogRef: RefObject<HTMLElement | null> };

export function InstallDialog({ pending, busy, t, onCancel, onConfirm, stopPropagation, deprecationDescription, dialogRef }: InstallProps) {
  return <div className="extension-permission-backdrop" role="presentation" onMouseDown={() => { if (!busy) onCancel(); }}><section ref={dialogRef} className="extension-permission-dialog extension-permission-dialog--install" role="dialog" aria-modal="true" aria-labelledby="extension-permission-title" tabIndex={-1} onMouseDown={stopPropagation}>
    <header><ShieldCheck size={18} strokeWidth={2} aria-hidden="true" /><div><h3 id="extension-permission-title">{t("settings.extensions.permissionTitle", { name: pending.review.extensionName })}</h3><p>{t("settings.extensions.permissionHint")}</p></div></header>
    <div className="extension-permission-dialog__body"><div className={`extension-install-trust${pending.review.officialVerified ? " extension-install-trust--official" : ""}`}>{pending.review.officialVerified ? <ShieldCheck size={17} strokeWidth={2} aria-hidden="true" /> : <Package size={17} strokeWidth={2} aria-hidden="true" />}<div><strong>{t(pending.review.officialVerified ? "settings.extensions.trustOfficial" : "settings.extensions.trustCommunity")}</strong><span>{t(pending.review.officialVerified ? "settings.extensions.trustOfficialDescription" : pending.review.publisherSigned ? "settings.extensions.trustSelfSignedDescription" : "settings.extensions.trustUnverifiedDescription")}</span></div></div>
      {pending.review.deprecation !== null && <div className="extension-install-deprecation" role="alert"><AlertTriangle size={17} strokeWidth={2} aria-hidden="true" /><div><strong>{t("settings.extensions.deprecatedTitle")}</strong><span>{deprecationDescription(pending.review.deprecation)}</span></div></div>}
      {pending.review.permissions.length > 0 && <section className="extension-permission-section"><h4>{t("settings.extensions.permissionCount", { count: pending.review.permissions.length })}</h4><div className="extension-permission-list">{pending.review.permissions.map((permission) => <div key={permission.permission}><Check size={14} strokeWidth={2} aria-hidden="true" /><div><strong>{permission.title}</strong><span>{permission.description}</span></div></div>)}</div></section>}
      <p className="extension-permission-dialog__boundary"><AlertCircle size={15} strokeWidth={2} aria-hidden="true" /><span>{t("settings.extensions.permissionReviewBoundary")}</span></p>
    </div><footer><button type="button" className="extensions-action-button" disabled={busy} onClick={onCancel}>{t("settings.extensions.cancel")}</button><button type="button" className={`extensions-action-button extensions-action-button--primary${pending.review.deprecation !== null ? " extensions-action-button--warning" : ""}`} data-dialog-initial disabled={busy} onClick={onConfirm}>{busy && <LoaderCircle className="extensions-spinner" size={14} strokeWidth={2} aria-hidden="true" />}{busy ? t("settings.extensions.installing") : t(pending.review.deprecation !== null ? "settings.extensions.installDeprecated" : "settings.extensions.approveInstall")}</button></footer>
  </section></div>;
}

export function LocalInstallDialog({ pending, busy, t, onCancel, onConfirm, stopPropagation, dialogRef }: LocalProps) {
  return <div className="extension-permission-backdrop" role="presentation" onMouseDown={() => { if (!busy) onCancel(); }}><section ref={dialogRef} className="extension-permission-dialog" role="dialog" aria-modal="true" aria-labelledby="extension-local-title" tabIndex={-1} onMouseDown={stopPropagation}>
    <header><ShieldCheck size={18} strokeWidth={2} aria-hidden="true" /><div><h3 id="extension-local-title">{t("settings.extensions.localConfirmTitle", { name: pending.name })}</h3><p>{t("settings.extensions.localConfirmHint")}</p></div></header>
    <div className="extension-permission-list"><div><strong>{t("settings.extensions.localSource")}</strong><span>{pending.source === "local" ? t("settings.extensions.localDirectory") : pending.source}</span></div><div><strong>{t("settings.extensions.localRuntime")}</strong><span>{pending.runtime}</span></div><div><strong>{t("settings.extensions.customPlatforms")}</strong><span>{pending.platforms.join(", ") || t("settings.extensions.unavailable")}</span></div>{pending.review.permissions.map((permission) => <div key={permission.permission}><strong>{permission.title}</strong><span>{permission.description}</span></div>)}<p className="extension-permission-dialog__boundary">{t("settings.extensions.permissionReviewBoundary")}</p></div>
    <footer><button type="button" className="extensions-action-button" disabled={busy} onClick={onCancel}>{t("settings.extensions.cancel")}</button><button type="button" className="extensions-action-button extensions-action-button--primary" data-dialog-initial disabled={busy} onClick={onConfirm}>{busy ? t("settings.extensions.installing") : t("settings.extensions.localConfirm")}</button></footer>
  </section></div>;
}
